/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  purge: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      backgroundImage: {
        cabinImage: "url('src/assets/cabin.jpeg')",
        cabin2: "url('src/assets/cabin_2.jpg')",
      },
      colors: {
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
      },
    },
    maxWidth: {
      50: "50%",
      60: "60%",
      70: "70%",
      80: "80%",
      90: "90%",
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
        "Playwrite DE Grund",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
    colors: {
      "reddish-brown-dark": "#766554",
      "reddish-brown-light": "#D1C5B8",
      "pine-green-dark": "#727459",
      "pine-green-light": "#B4B99B",
      "soft-bronze-light": "#E8CDBE",
      "soft-bronze-dark": "#D69B7C",
      "purple-mauve-dark": "#866E84",
      "purple-mauve-light": "#D7C7D5",
      "mustard-brown-dark": "#998670",
      "mustard-brown-light": "#E3D3C0",
      white: "#FFFFFF",
    },
    textColor: {
      white: "#FFFFFF",
      "reddish-brown-light": "#D1C5B8",
      "mustard-brown-light": "#E3D3C0",
    },
    fontFamily: {
      Edu: ["Edu VIC WA NT Beginner", "sans-serif"],
      Playwrite: ["Playwrite DE Grund", "sans-serif"],
      Delius: ["Delius Unicase", "sans-serif"],
      Dekko: ["Dekko", "sans-serif"],
    },
  },
  plugins: [],
};
